// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glass-variants/AppleGlass.tsx": () => import("../components/mockups/glass-variants/AppleGlass.tsx"),
  "./components/mockups/glass-variants/DarkGlass.tsx": () => import("../components/mockups/glass-variants/DarkGlass.tsx"),
  "./components/mockups/glass-variants/FrostGlass.tsx": () => import("../components/mockups/glass-variants/FrostGlass.tsx"),
  "./components/mockups/glass-variants/NeonGlass.tsx": () => import("../components/mockups/glass-variants/NeonGlass.tsx")
};
